application: tentapp
version: 1
runtime: python
api_version: 1

inbound_services:

- mail
- xmpp_message

handlers:

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml
  secure: optional

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: 1d
  secure: optional

- url: /.static
  static_dir: static
  secure: optional

- url: /.remote/.*
  script: /tentapp/handler/remote.py
  secure: always

- url: /_ah/mail/.*
  script: /tentapp/handler/mail.py
  login: admin

- url: /_ah/xmpp/message/chat/.*
  script: /tentapp/handler/xmpp.py
  login: admin

- url: .*
  script: /tentapp/main.py
  secure: optional
