site_author: Ampify Authors
site_description: The Ampify Platform
site_license: Public Domain
site_title: Ampify
site_url: http://code.ampify.it

analytics_id: UA-90176-26
section_id: code
typekit: enabled

index_pages:
- archive.html: archive.genshi
